Hostname = dpg-d0j0ahq4d50c73e1rdu0-a
Port = 5432
Database = montecarlo
Username = hive
Password = 5Bhn7S9K15K4O0tEvDXiLvL7RZTQ8V8A
Internal Database URL = postgresql://hive:5Bhn7S9K15K4O0tEvDXiLvL7RZTQ8V8A@dpg-d0j0ahq4d50c73e1rdu0-a/montecarlo
External Database URL = postgresql://hive:5Bhn7S9K15K4O0tEvDXiLvL7RZTQ8V8A@dpg-d0j0ahq4d50c73e1rdu0-a.oregon-postgres.render.com/montecarlo
PSQL Command = PGPASSWORD=5Bhn7S9K15K4O0tEvDXiLvL7RZTQ8V8A psql -h dpg-d0j0ahq4d50c73e1rdu0-a.oregon-postgres.render.com -U hive montecarlo



SECRET_KEY=U3u-VI3Uv6lLO9-NFwYiS87w8YzBAHVfQTgwM1lka7Q
DATABASE_URL=postgresql://hive:5Bhn7S9K15K4O0tEvDXiLvL7RZTQ8V8A@dpg-d0j0ahq4d50c73e1rdu0-a/montecarlo