# fly.toml app configuration file generated for montecarlo-app on 2025-05-15T09:17:46-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = 'montecarlo-app'
primary_region = 'iad'

[build]
  image = "python:3.11.9-slim"

[env]
  PORT = "8080"

[[mounts]]
  source = 'data'
  destination = '/mnt/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

